### PR TITLE
Unable to record 'Date Check Written' field as it is rendered twice in the form

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by JoeMurray** [comment]
Could you also post about data recovery?

**Comment by seamuslee001** [comment]
@monishdeb I did a test of this on staging, 

I found that it worked correctly when changing FTs and also when changing payment processors and confirmed that the date is correctly saved when entered.

However I did find an issue which I don't know if this is due to these changes or other changes which is that after navigating to a contact's contribution tab and adding in a contribution, If you go to click add contribution again i.e. the Date Check Written field doesn't show up at all. It takes reloading the whole page to get it to show again

**Comment by monishdeb** [comment]
Good catch ... yes its glitch due to the recent fix on page reload. Updated the PR with this [commit](https://github.com/JMAConsulting/biz.jmaconsulting.ehc/pull/9/commits/90fd588f944105481e7216538df1ec4b2179f9b1) . Its working correctly now:
before

**Comment by seamuslee001** [comment]
Re-tested and confirmed this works on staging

**Pull request merged**
